name: CI

on:
  push:
    branches:
      - main
      - master
      - ghcr
  pull_request:
    branches:
      - main
      - master
      - ghcr

env:
  NODE_IMAGE: node:25-alpine3.23

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ${{ env.NODE_IMAGE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: ESLint
        run: npm run lint

      - name: Typecheck
        run: npx tsc --noEmit
